import React from 'react';

const Text = () => {
    return (
        <div>
               <div className='text-center mb-11 mt-11'>
                <h1 className='text-4xl font-bold'>Our Service Card </h1>
              <br />
                <p>Men's and Boy's Haircuts: ...
                    Scalp Massage & Conditioning Treatment: ...
                    Straight Razor and Wet Shave: ...
                    Beard Sculpting: ...
                    Be on Time. ...
                    Clean Your Hair. ...
                    Know the Cut You Want. ...
                    Have Patience.</p>
            </div>
        </div>
    );
};

export default Text;